[graph]
# Cargo deny will check dependencies via `--all-features`
all-features = true

[advisories]
version = 2
ignore = [
{ id = "RUSTSEC-2024-0320", reason = "waiting for `config` crate to update" },
{ id = "RUSTSEC-2021-0137", reason = "todo: switch to alkali" },
{ id = "RUSTSEC-2021-0140", reason = "todo: update rxing to a newer imageproc crate so that it removes the unmaintained rusttype dep" },
{ id = "RUSTSEC-2024-0375", reason = "todo: update clap" },
{ id = "RUSTSEC-2024-0370", reason = "todo: update clap" },
{ id = "RUSTSEC-2021-0153", reason = "todo: update rxing" },
{ id = "RUSTSEC-2021-0145", reason = "todo: update clap" },
]

[sources]
unknown-registry = "deny"

[licenses]
version = 2
# We want really high confidence when inferring licenses from text
confidence-threshold = 1.0
unused-allowed-license = "allow"

# List of explicitly allowed licenses
# See https://spdx.org/licenses/ for list of possible licenses
allow = [
    "0BSD",
    "Apache-2.0 WITH LLVM-exception",
    "Apache-2.0",
    "BSD-2-Clause",
    "BSD-2-Clause-Patent",
    "BSD-3-Clause",
    "BSL-1.0",
    "CC0-1.0",
    "ISC",
    "LicenseRef-UFL-1.0",
    "LicenseRef-ring",
    "MIT",
    "MPL-2.0", # Although this is copyleft, it is scoped to modifying the original files
    "OFL-1.1",
    "OpenSSL",
    "Unicode-DFS-2016",
    "Unlicense",
    "Zlib",
]

[[licenses.exceptions]]
# PMD does not release FOSS apis for their camera :(
name = "royale-sys"
allow = ["LicenseRef-pmd-proprietary"]
version = "0.0.0"

[[licenses.exceptions]]
# Seek Thermal does not release FOSS apis for their camera :(
name = "seekcamera-sys"
allow = ["LicenseRef-seek-proprietary"]
version = "0.0.0"


# See https://github.com/briansmith/ring/blob/95948b3977013aed16db92ae32e6b8384496a740/deny.toml#L12
[[licenses.clarify]]
name = "ring"
expression = "LicenseRef-ring"
license-files = [
    { path = "LICENSE", hash = 0xbd0eed23 },
]
