[package]
name = "orb-royale"
version = "0.1.0"
edition.workspace = true
license.workspace = true
publish = false

[dependencies]
thiserror.workspace = true

[target.'cfg(all(target_arch = "aarch64", target_os = "linux"))'.dependencies.royale-sys]
path = "../royale-sys"
