[package]
name = "orb-seekcamera"
version = "0.1.0"
edition.workspace = true
license.workspace = true
publish = false

[dependencies]
log.workspace = true
rkyv.workspace = true
thiserror.workspace = true

[dependencies.seekcamera-sys]
path = "../seekcamera-sys"
