[package]
name = "tmp-tracing"
version = "0.0.0"
edition.workspace = true
license.workspace = true
publish = false

description = "Fake tracing crate, which just reexports log"

[dependencies]
log.workspace = true
