[package]
name = "orb-id"
version = "0.1.0"
edition.workspace = true
license.workspace = true
description = "Interface to read the orb-id from the fusebanks"

[dependencies]
color-eyre.workspace = true
eyre.workspace = true
