[package]
name = "v4l2-sys"
version = "0.1.0"
authors = ["Valentine Valyaeff <valentine.valyaeff@gmail.com>"]
edition.workspace = true
license.workspace = true
publish = false

[build-dependencies]
bindgen.workspace = true
color-eyre.workspace = true
