[package]
name = "royale-sys"
version = "0.0.0"
edition.workspace = true
license = "LicenseRef-pmd-proprietary"
publish = false

[build-dependencies]
bindgen.workspace = true
cc.workspace = true
color-eyre.workspace = true
