[package]
name = "seekcamera-sys"
version = "0.0.0"
edition.workspace = true
license = "LicenseRef-seek-proprietary"
publish = false

[build-dependencies]
bindgen.workspace = true
color-eyre.workspace = true
