[package]
name = "fraud-engine"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[dependencies]
evalexpr = "11.3.0"
eyre.workspace = true
schemars.workspace = true
serde.workspace = true
serde_json.workspace = true
tracing.workspace = true
