name: Test if Devcontainer is building on x86_64

on:
  pull_request:
    paths:
      - .devcontainers/**
      - flake.nix
      - flake.lock
  push:
    branches:
      - master

jobs:
  test_build:
    runs-on: ubuntu-22.04-32core
    steps:
      - name: Check out code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # pin@v2v4.1.7
      - name: Pre-build dev container image
        uses: devcontainers/ci@a56d055efecd725e8cfe370543b6071b79989cc8 # pin@v0.3.1900000349
        env:
          CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GIT_HUB_TOKEN }}
